[features]
seeds = false
[programs.localnet]
solana_twitter = "BZvPErdwUEKjFk76hT2Z4FGqAwmf8k2cVRpL9wTHswVN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/jota/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-test = "echo 'Hello world!'"

